@startuml
class Inventory{
    -Arraylist<InventoryItem> inventory

    +void readJson()
    +search product(String Name)
}
class InventoryItem{
    -String name
    -Double price
    -int quantity
}
InventoryItem--|>Inventory
@enduml